title: Insight Insure
description: Consumer-first insurance advice and comparisons
theme: minima
baseurl: "/insightinsure"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
