title: Insight Insure
description: Consumer-first insurance advice and comparisons
theme: minima
baseurl: ""
url: "https://insightinsure.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
